server:
  port: 8888
spring:
  application:
    name: spring-boot-mq-consumer

  activemq:
    broker-url: tcp://192.168.137.135:61616

    user: admin
    password: admin
  jms:
    pub-sub-domain: true
#    pub-sub-domain: false
myQueue: boot-active-mq
myTopic: boot-active-mq-topic
